title: Bilal MAJJAD
description: This is Bilal MAJJAD personal page, you can find more information on his old and ongoing project
show_downloads: false
google_analytics: G-QTNDKBBZ67
theme: jekyll-theme-hacker
twitter: byhlel
github_username: byhlel
